---
title: "LGCP log Intensity Surfaces"
---

```{r}
library(nimble)
library(ggplot2)
library(fields)  # for rdist
library(glue)
library(dplyr)
library(sf)
library(sp)
library(spatstat)
library(reshape2)
library(raster)  # for the count plot in the very end
library(coda)
library(invgamma)
library(ggmap)
```

        
NOTE: The .Rda files were generated using src/zhihan/lgcp_uof_optimized_6_covariates.Rmd, then loaded in here.
        
```{r}
load("lgcp_sus_uof_6cov_3million_samples_20000_int_pts.Rda")
```

```{r}
# make plotting faster
every <- 1000
samples_for_plotting <- samples[seq(1, nrow(samples), every), ]
```

```{r}
library(zoo)

n_samples <- nrow(samples_for_plotting)

ggplot() + 
  geom_line(aes(
    x=1:n_samples * every, 
    y=samples_for_plotting[, ncol(samples_for_plotting) - 1]
  ), color="black") + 
  ylab("Log-likelihood on a log scale") + 
  xlab("Iteration")

ggplot() + 
  geom_abline(intercept=0, slope=0) +
  geom_line(aes(x=1:n_samples * every, y=samples_for_plotting[, 1], color="beta0")) + 
  geom_line(aes(x=1:n_samples * every, y=samples_for_plotting[, 2], color="beta1 (Total Population)")) + 
  geom_line(aes(x=1:n_samples * every, y=samples_for_plotting[, 3], color="beta2 (Median Household Income)")) +
  geom_line(aes(x=1:n_samples * every, y=samples_for_plotting[, 4], color="beta3 (Perc. Female)")) +
  geom_line(aes(x=1:n_samples * every, y=samples_for_plotting[, 5], color="beta4 (Herfendahl Index)")) +
  geom_line(aes(x=1:n_samples * every, y=samples_for_plotting[, 6], color="beta5 (Perc. Unemployed)")) +
  geom_line(aes(x=1:n_samples * every, y=samples_for_plotting[, 7], color="beta6 (Perc. Foodstamp)")) +
  scale_color_manual(
    name = "Regression\nCoefficients", 
    values = c(
      "beta0" = "black", 
      "beta1 (Total Population)" = "red", 
      "beta2 (Median Household Income)" = "orange", 
      "beta3 (Perc. Female)" = "green",
      "beta4 (Herfendahl Index)" = "blue",
      "beta5 (Perc. Unemployed)" = "purple",
      "beta6 (Perc. Foodstamp)" = "pink"
    )
  ) + 
  xlab("Iteration") + 
  ylab("Value")

melted_samples <- melt(cbind(1:n_samples, samples_for_plotting[, 8:9]), id.vars="1:n_samples")
colnames(melted_samples)[1] <- "index"

ggplot() +
  geom_line(data=melted_samples, aes(x=index * every, y=value, color=variable)) +
  xlab("Iteration") +
  ylab("GP values (on a 2 knots)") +
  theme(legend.position="none")

ggplot() + 
  geom_line(aes(x=1:n_samples * every, y=samples_for_plotting[, ncol(samples)])) + 
  geom_abline(intercept=1, slope=0, linetype="dashed", color="black") +
  xlab("Iteration") +
  ylab("Sigma")
```

```{r}
samples_no_burnin <- samples[2000000:3000000, ]
```

```{r}
colMeans(samples_no_burnin[1:7])
```

```{r}
effectiveSize(samples_no_burnin[1:7])
```

```{r}
effectiveSize(samples_no_burnin[ncol(samples_no_burnin)])
```

```{r}
# mcmc_intervals(samples_no_burnin[2:7], prob_outer=0.95, prob=0.5, outer_size=5, inner_size=5, point_size=2) + 
#   scale_y_discrete(
#     labels = c(
#       "beta1" = "beta1 (normalized total population)",
#       "beta2" = "beta2 (normalized median household income)",
#       "beta3" = "beta3 (percent female)",
#       "beta4" = "beta4 (Herfendahl index)",
#       "beta5" = "beta5 (percent unemployed)",
#       "beta6" = "beta6 (percent foodstamp)"
#     )
#   )
```


# Log-intensity surface over integration points

```{r}
ward9_map <- get_map(c(left = -93.28, bottom = 44.93, 
                         right = -93.225, top = 44.965), source = "stamen")
#ward8_map <- ggmap(get_map(c(left = -93.294, bottom = 44.908, 
#                            right = -93.244, top = 44.9521), source = "stamen"))
```

```{r}
# matrix(c(1, 1, 1, 1, 1, 1, 1, 1, 1), nrow=3) * c(1, 2, 3)
```

```{r}
#int_data <- read.csv("../../data/working/ward_9_blockgroups/over_simpoints_cov_10000int_points.csv")
int_data <- read.csv("../../data/working/ward_9_blockgroups/over_simpoints_cov_20000int_points.csv")
#int_data <- read.csv("../../data/working/ward_8_blockgroups/over_simpoints_cov_10000int_points2.csv")

int_pts <- int_data[, c("x", "y")]

int_cov <- int_data[, c("total_pop", "med_hh_income", "perc_female", "herfendahl", "perc_unemployed", "perc_foodstamp")]
# int_cov <- int_data[, c("total_pop", "med_hh_income")]

int_cov$total_pop = int_cov$total_pop / 2193
int_cov$med_hh_income = int_cov$med_hh_income / 110208
#int_cov$total_pop = int_cov$total_pop / 1837
#int_cov$med_hh_income = int_cov$med_hh_income / 130563
```

```{r}
knots <- read.csv("../../data/working/ward_9_blockgroups/71_knots.csv")
#knots <- read.csv("../../data/working/ward_8_blockgroups/90_knots.csv")
```

```{r}
expcov <- nimbleFunction(run = function(dists = double(2), phi = double(0), sigma = double(0)) {
    returnType(double(2))
    sigma2 <- sigma*sigma
    result <- sigma2*exp(-dists/phi)
    return(result)
})
```

```{r}
# distance matrices
knots_dists <- rdist(knots, knots)
integration_pts_vs_knots_dists <- rdist(int_pts, knots)

# fix phi
dist_95 <- as.numeric(quantile(knots_dists, probs = c(0.95)))
dist_05 <- as.numeric(quantile(knots_dists, probs = c(0.05)))
#deciding range 
upper_unif <- -dist_95/log(0.05)
lower_unif <- -dist_05/log(0.95)
#deciding fixed value for phi
fix_phi <- (upper_unif+lower_unif)/2
fix_phi

knots_cov = expcov(knots_dists, phi=fix_phi, sigma=1)
integration_pts_vs_knots_cov = expcov(integration_pts_vs_knots_dists, phi=fix_phi, sigma=1)
```

```{r}
load("../../data/working/ward_9_blockgroups/Ward9_Blocks.Rdata")
#load("../../data/working/ward_8_blockgroups/Ward8_Blocks.Rdata")
```

```{r}
covs_int <- int_cov
covs_int <- cbind(rep(1, nrow(covs_int)), covs_int)

beta_means <- colMeans(samples_no_burnin[,1:7])
gp_means <- colMeans(samples_no_burnin[,8:(ncol(samples)-2)] * samples_no_burnin[,ncol(samples)])

# here are everything that can be plotted
log_intensities <- as.matrix(covs_int) %*% as.matrix(beta_means) + integration_pts_vs_knots_cov %*% solve(knots_cov) %*% gp_means
log_intensities_no_gp <- as.matrix(covs_int) %*% as.matrix(beta_means)
gp <- integration_pts_vs_knots_cov %*% solve(knots_cov) %*% gp_means
log_intensities_exp <- exp(log_intensities)

ggmap(ward9_map) +
  geom_point(data=int_pts, aes(x = x, y = y, color = log_intensities), size=2.6, shape=15) +
  scale_color_viridis(name='Log intensity') +
  geom_polygon(data=ward9_blocks, aes(x = long, y = lat, group = group), fill=NA, color="black") +
  coord_fixed() +
  #geom_point(data=obs_pts, aes(x=X, y=Y), alpha=1, shape=1) +
  #xlab("Longitude") +
  #ylab("Latitude") +
  #ggtitle("Log intensity surface of suspicious people in ward 9") +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank())

# ward8_blocks_fortify <- broom::tidy(ward8_blocks)
# ward8_blocks$id <- row.names(ward8_blocks)
# ward8_blocks_fortify <- left_join(ward8_blocks_fortify, ward8_blocks@data)
# 
# ggmap(get_map(c(left = -93.294, bottom = 44.908, 
#                             right = -93.244, top = 44.9521), source = "stamen")) + 
#   geom_point(data=int_pts, aes(x = x, y = y, color = log_intensities), size=2.6, shape=15) +
#   scale_color_viridis(name='Log intensity') + 
#   geom_polygon(data=ward8_blocks_fortify, aes(x = long, y = lat, group = group), fill=NA, color="black") + 
#   coord_fixed() +
#   #geom_point(data=obs_pts, aes(x=X, y=Y), alpha=1, shape=1) + 
#   #xlab("Longitude") + 
#   #ylab("Latitude") + 
#   ggtitle("Log intensity surface of all use-of-force incidents in ward 8") + 
#   theme(axis.title = element_blank(),
#         axis.text = element_blank(),
#         axis.ticks = element_blank())
```


This is for plotting NHPP
```{r}
load("../../data/working/ward_9_blockgroups/Ward9_Blocks.Rdata")
#colMeans(samples_no_burnin[1:7])
ward9_blocks@data$total_pop = ward9_blocks@data$total_pop / 2193
ward9_blocks@data$med_hh_income = ward9_blocks@data$med_hh_income / 110208

#Generated by using src/zhihan/lgcp_uof_optimized_6_covariates.Rmd, and only running the elements for an NHPP, then removing
#burn-in and finding the means for each column to get the coefficients.
ward9_blocks@data$log_intensities <- 13.6108876 + 0.5110273*ward9_blocks@data$total_pop + 0.9545238*ward9_blocks@data$med_hh_income + 1.3430121*ward9_blocks@data$perc_female + -1.9854064*ward9_blocks@data$herfendahl + 0.4226685*ward9_blocks@data$perc_unemployed + 3.0574235*ward9_blocks@data$perc_foodstamp

ward9_blocks_fortify <- broom::tidy(ward9_blocks)
ward9_blocks$id <- row.names(ward9_blocks)
ward9_blocks_fortify <- left_join(ward9_blocks_fortify, ward9_blocks@data)

ggmap(ward9_map) + 
  #geom_point(data=samples_no_burnin, aes(x = x, y = y, color = intensity), size=2.6, shape=15) +
  geom_polygon(data=ward9_blocks_fortify, aes(x = long, y = lat, group = group, fill = log_intensities), color="black") + 
  coord_fixed() +
  scale_fill_viridis(name='Log intensity') + 
  #geom_point(data=obs_pts, aes(x=X, y=Y), alpha=1, shape=1) + 
  #xlab("Longitude") + 
  #ylab("Latitude") + 
  #ggtitle("Log intensity surface of all use-of-force incidents (over Ward 9 Minneapolis)") + 
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank())
```

