---
title: "census_data_overlay"
author: "Aya Klos"
date: "2023-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sp)
library(tigris)
library(ggmap)
library(tidycensus)
library(maditr)
library(spdep)
library(spatialreg)
library(gridExtra)
library(sf)
```

```{r}
rm(list = ls())
```

```{r}
crime_data <- read.csv("/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/original/Crime_Data.csv")
use_of_force_data <- read.csv("/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/original/Police_Use_of_Force.csv")
police_incidents_data <- read.csv("/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/working/Police_Incidents.csv")

#Minneapolis census tracts
minn_tracts <- tracts("Minnesota", c("Hennepin"))
minn_tracts <- as_Spatial(minn_tracts)

#subset to only tracts of interest (may not be appropriate for other states)
# minn_tracts <- minn_tracts[-which(minn_tracts$ALAND ==0 & minn_tracts$AWATER >0),]

#download map of Minneapolis, find the coordinates on Google Maps
minn_map <- ggmap(get_map(c(left = -93.35, bottom = 44.88, 
                            right = -93.18, top = 45.06), source = "stamen"))
```

Aggregating spatial data in R (review)
```{r}
#now we need to convert points to a spatial dataset
coordinates(crime_data) <- ~X+Y
proj4string(crime_data)

coordinates(use_of_force_data) <- ~X+Y
proj4string(use_of_force_data)

coordinates(police_incidents_data) <- ~Long+Lat
proj4string(police_incidents_data)


#need to assign projection
proj4string(crime_data) <- proj4string(minn_tracts)
proj4string(use_of_force_data) <- proj4string(minn_tracts)
proj4string(police_incidents_data) <- proj4string(minn_tracts) 

#are they all in city limits?
over_minn_crime <- over(crime_data, minn_tracts)
over_minn_uof <- over(use_of_force_data, minn_tracts)

length(which(is.na(over_minn_crime$GEOID))) #1323 are outside of the census tracts shown here
length(which(is.na(over_minn_uof$GEOID))) #1601 are outside of the census tracts shown here

#remove the points outside of the city
crime_data <- crime_data[-which(is.na(over_minn_crime$GEOID)),] %>% as.data.frame()
use_of_force_data <- use_of_force_data[-which(is.na(over_minn_uof$GEOID)),] %>% as.data.frame()

#now need to aggregate by tract
agg_dat.crime <- plyr::count(over_minn_crime, c('GEOID'))
agg_dat.crime$GEOID <- as.factor(agg_dat.crime$GEOID)
colnames(agg_dat.crime) <- c("GEOID", "num_crime")

agg_dat.uof <- plyr::count(over_minn_uof, c('GEOID'))
agg_dat.uof$GEOID <- as.factor(agg_dat.uof$GEOID)
colnames(agg_dat.uof) <- c("GEOID", "num_uof")

#join to geographic data
minn_tracts@data <- left_join(minn_tracts@data, agg_dat.crime, by = (GEOID = "GEOID"))
minn_tracts@data <- left_join(minn_tracts@data, agg_dat.uof, by = (GEOID = "GEOID"))
```

Now let's plot the number of crimes by tract.
```{r}
#need to format data so ggplot knows what to do with it
minn_fortify <- broom::tidy(minn_tracts)
minn_tracts$id <- row.names(minn_tracts)
minn_fortify <- left_join(minn_fortify, minn_tracts@data)

#replot the shapefile
minn_map + geom_polygon(data= minn_fortify, aes(x = long, y = lat, group = group, fill = num_crime), col = "black")
```

```{r}
#this is review from last time, collecting census data
minn_census <- get_acs(geography = "tract", 
                         variables = c("B01003_001E", 
                                       "B01001_002E", "B01001_026E",
                                       "B02008_001E", "B02009_001E", 
                                       "B02010_001E", "B02011_001E", 
                                       "B02012_001E", "B02013_001E", 
                                       "B03001_002E", "B03001_003E", 
                                       "B06011_001E", "B06012_002E", 
                                       "B06012_003E", "B23025_003E", 
                                       "B23025_004E", "B23025_005E"), year = 2021,
                         state = "MN", county = c("Hennepin County"), 
                         geometry = F)

code_book_mn <- rbind(c("B01003_001", "total_pop"),
                   c("B01001_002", "total_male"),
                   c("B01001_026", "total_female"),
                   c("B02008_001", "total_white"), 
                   c("B02009_001", "total_black"), 
                   c("B02010_001", "total_native"), 
                   c("B02011_001", "total_asian"), 
                   c("B02012_001", "total_islander"), 
                   c("B02013_001", "total_otherrace"), 
                   c("B03001_002", "total_not_hispanic"), 
                   c("B03001_003", "total_hispanic"), 
                   c("B06011_001", "med_income"), 
                   c("B06012_002", "below_pov_level"), 
                   c("B06012_003", "100_149_above_pov_level"), 
                   c("B23025_003", "total_labor_force"), 
                   c("B23025_004", "total_employed"), 
                   c("B23025_005", "total_unemployed"))

#join to the Census data
code_book_mn <- as.data.frame(code_book_mn)
colnames(code_book_mn) <- c("variable", "var_name")

#joining census data and codebook
minn_census <- left_join(minn_census, code_book_mn)

#format the data so there is a row for each census tract and column for every variable
minn_acs_data <- maditr::dcast(minn_census, GEOID ~ var_name, value.var = "estimate", fun.aggregate = NULL)

#subset to only data that is in the shape file
minn_acs_data <- minn_acs_data[which(minn_acs_data$GEOID %in% minn_tracts$GEOID),]   

# Combine dataset with spatial dataset by GEOID
minn_tracts@data <- left_join(minn_tracts@data, minn_acs_data)

```

Plot census data
```{r}
#plotting code from last time
minn_fortify <- broom::tidy(minn_tracts)
minn_tracts$id <- row.names(minn_tracts)
minn_fortify <- left_join(minn_fortify, minn_tracts@data)

#replot the shapefile
minn_map + geom_polygon(data= minn_fortify, 
                          aes(x = long, y = lat, group = group, 
                              fill = total_unemployed), col = "black")
```

```{r}
over_minn_crime_census <- left_join(over_minn_crime, minn_acs_data, by = "GEOID")
over_minn_uof_census <- left_join(over_minn_uof, minn_acs_data, by = "GEOID")
```

Overlaying point-level data sets onto census tracts that overlap with wards:
```{r}
load("/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/working/Census_Tracts_Data.Rdata")
crime_data <- read.csv("/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/original/Crime_Data.csv")
use_of_force_data <- read.csv("/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/original/Police_Use_of_Force.csv")
police_incidents_data <- read.csv("/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/working/Police_Incidents.csv")
uof_suspicious_data <- use_of_force_data %>% filter(Problem == "Suspicious Person ")

coordinates(crime_data) <- ~X+Y
coordinates(use_of_force_data) <- ~X+Y
coordinates(police_incidents_data) <- ~Long+Lat
coordinates(uof_suspicious_data) <- ~X+Y

proj4string(crime_data) <- proj4string(minneapolis_tracts)
proj4string(use_of_force_data) <- proj4string(minneapolis_tracts)
proj4string(police_incidents_data) <- proj4string(minneapolis_tracts) 
proj4string(uof_suspicious_data) <- proj4string(minneapolis_tracts)

over_minn_crime <- over(crime_data, minneapolis_tracts)
over_minn_uof <- over(use_of_force_data, minneapolis_tracts)
over_minn_pi <- over(police_incidents_data, minneapolis_tracts)

# write.csv(over_minn_crime, file="/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/working/overlay_pointdatasets_censusdata/over_crime_census.csv")
# write.csv(over_minn_uof, file="/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/working/overlay_pointdatasets_censusdata/over_uof_census.csv")
# write.csv(over_minn_pi, file="/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/working/overlay_pointdatasets_censusdata/over_pi_census.csv")

over_minn_uof_sus <- over(uof_suspicious_data, minneapolis_tracts)
```

Trying out Harper's plot:

```{r}
minn_wards <- st_read("/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/original/City_Council_Wards/WARDS.shp") %>%
  as_Spatial()
wards_fortify <- broom::tidy(minn_wards)
minn_wards$id <- row.names(minn_wards)
wards_fortify <- left_join(wards_fortify, minn_wards@data)

minn_map + 
  geom_polygon(data = minn_fortify, 
               aes(x = long, y = lat, group = group),
               fill = "gray", col = "black") +
  geom_polygon(data= wards_fortify, 
                        aes(x = long, y = lat, group = group), 
                        fill = NA, col = "red") +
  geom_polygon(data = wards_fortify %>% filter(id == 2), 
                        aes(x = long, y = lat, group = group), 
                        fill = "blue", col = "red", alpha = 0.5)
```

Trying to find intersections:

```{r}
minn_ward9 <- st_read("/Users/ayaklos/Documents/GitHub/carleton_comps_22_23/data/original/City_Council_Wards/WARDS.shp") %>% filter(FID == 2) %>%
  as_Spatial()

minn_ward9.sf <-st_as_sf(minn_ward9)
minn_tracts.sf <-st_as_sf(minn_tracts)

intersect_ward9_tracts <- st_intersection(minn_tracts.sf, minn_ward9.sf)
```